fix(mw): Make invokeOptions a non-optional type
redwoodjs/redwood pull request #10537
Opened 2024-05-03 13:25 UTC by dac09

Found an issue while writing up the blogpost on middleware. 

The invokeOptions is always supplied, but may not always be used.

2024-05-04 02:32 UTC, cannikin approved these changes

2024-05-04 06:36 UTC, Tobbe commented
@dac09 I don't understand why you had to change to use an object here. Can you please try to explain in a bit more detail so even I can follow along 😄

2024-05-04 06:40 UTC, Tobbe commented on .changesets/10537.md
> +The invokeOptions is always supplied when invoking middleware, but may not always be used.
Can you please explain this a bit more? 🙏

2024-05-04 06:41 UTC, Tobbe requested changes
See my other comments

2024-05-07 07:32 UTC, dac09 commented
> @dac09 I don't understand why you had to change to use an object here. Can you please try to explain in a bit more detail so even I can follow along 😄

Sure. In TS you cannot supply an optional third parameter after a required parameter (the middleware function). https://stackoverflow.com/questions/46958782/why-does-typescript-require-optional-parameters-after-required-parameters

> It should be fine to pass invokeOptions even if they're not used. The receiving function can just ignore the parameter I think

Exactly. My original type was that invoke options was optional, which is incorrect. Invoke options are always supplied, even if the middleware is undefined. This happens when the middleware router doesn't find a match. The logic for whether to excecute the middleware sits inside the invoke function.

2024-05-09 14:52 UTC, Tobbe commented
> In TS you cannot supply an required third parameter after a optional parameter

Yeah, that much I knew. What you can usually do in those cases is to use method overloading. So I was going to suggest that. But thinking about it some more I think I prefer the options object that you've used here. It makes it more explicit what each of the arguments are 👍 (And to really drive that home I suggest you rename `req` to `request` in the options object)

2024-05-10 10:48 UTC, dac09 commented
> Now the case may be that the third option is in all practical cases in fact passed to the function. But that doesn't change the fact that for the function itself the third parameter is still optional 🙂

Hmm you're right in that it CAN be optional, I was focusing on the auth ones and not the cases where you might register a middleware to handle POST requests (like an API endpoint).

I'll close this for now, and come back if required.

2024-05-10 10:48 UTC, closed without merging