feat: add customize content type parsers for api plugin
redwoodjs/redwood pull request #10573
Opened 2024-05-15 17:27 UTC by Josh-Walker-GM

Alterations to #10449

2024-05-20 15:36 UTC, Josh-Walker-GM commented on docs/docs/docker.md
> +  configureApiServer(server){
Need to edit this so it's not `server` oops

2024-05-20 15:36 UTC, Josh-Walker-GM commented on docs/docs/docker.md
> +  async configureApiServer(server) {
Again this parameter can't be called `server` in this code right here

2024-05-20 20:44 UTC, dthyresson commented on packages/api-server/src/plugins/api.ts
> +  // Run users custom server configuration function
Note @Josh-Walker-GM and I found that the order where custom server config was added matters - if after loading functions, then plugins like fastify complress did not work properly.

2024-05-20 21:04 UTC, dthyresson requested changes
@Josh-Walker-GM I confirmed I could compress api requests:

<img width="1307" alt="image" src="https://github.com/redwoodjs/redwood/assets/1051633/f94d1ac8-ee4e-442a-8e93-243ea2d86115">


But, graphql requests are not.

<img width="1171" alt="image" src="https://github.com/redwoodjs/redwood/assets/1051633/dceed137-8086-45dd-be45-521e495f3218">


Can we add that -- or should we always compress both for api and graphql servers?

We'd still need this in createServer if the user decide to mount and server more that just the api and graphql, but we do want to let people compress graphql responses.

Also - is this a breaking change? If people use register, they will have to reconfigure their server.

2024-05-20 21:22 UTC, dthyresson commented
@Josh-Walker-GM Should we add:

```
async function main() {
  const server = await createServer({
    logger,
    async configureApiServer(s) {
      await s.register(import('@fastify/compress'), {
        global: true,
        threshold: 1024,
        encodings: ['deflate', 'gzip'],
      })
    },
    async configureGraphQLServer(s) {
      await s.register(import('@fastify/compress'), {
        global: true,
        threshold: 1024,
        encodings: ['deflate', 'gzip'],
      })
    },
``` ?

In case want graphql function to handle differently?

2024-05-22 13:47 UTC, dthyresson approved these changes

2024-05-22 13:48 UTC, dthyresson commented
@Josh-Walker-GM sounds good I’ll make an issue for GraphQL compression as well

2024-05-22 14:12 UTC, Tobbe commented on docs/docs/docker.md
> +    s.addContentTypeParser(/^image\/.*/, (req, payload, done) => {
```suggestion
    server.addContentTypeParser(/^image\/.*/, (_req, payload, done) => {
```
`req` is not used

2024-05-22 14:18 UTC, Tobbe commented on docs/docs/docker.md
> +  async configureApiServer(s) {
Interesting. I'd assume it would shadow the outer `server` variable 🤔

2024-06-05 21:42 UTC, merged