Updates to the FlightControl deployment
redwoodjs/redwood pull request #10716
Opened 2024-06-02 19:05 UTC by ajoslin103

The Flightcontrol has changed a little bit - and Redwood has better support

I got my RW deployed and wanted to update the Docs

2024-06-03 06:44 UTC, Tobbe reviewed
Thanks a lot for your PR @ajoslin103

2024-06-03 13:02 UTC, ajoslin103 commented on docs/docs/deploy/flightcontrol.md
>  NOTE: If you are using yarn v1, remove the `installCommand`'s from flightcontrol.json
👍

2024-06-03 13:03 UTC, ajoslin103 commented on docs/docs/deploy/flightcontrol.md
> +2. NOTE: The RedwoodJS Flightcontrol setup defaults to an environment[0] of 'Development'
Nope!  Nice catch!

2024-06-07 06:28 UTC, Tobbe requested changes
Sorry, I found a couple of more things

2024-06-07 06:28 UTC, Tobbe commented on docs/docs/deploy/flightcontrol.md
> +[Flightcontrol](https://www.flightcontrol.dev) enables any developer to deploy to AWS without being a wizard. It's extremely easy to use but lets you pop the hood and leverage the raw power of AWS wh
I'd leave the `ref` in there. IIRC someone from flightcontrol first wrote these docs, so they probably want that to better know where their traffic is coming from 
```suggestion
[Flightcontrol](https://www.flightcontrol.dev?ref=redwoodv) enables any developer to deploy to AWS without being a wizard. It's extremely easy to use but lets you pop the hood and leverage the raw power of AWS when needed. It supports servers, static sites, and databases which makes it a perfect fit for hosting scalable Redwood apps.
```

2024-06-07 06:28 UTC, Tobbe commented on docs/docs/deploy/flightcontrol.md
> +    4. NOTE: `flightcontrol.json` is now the source of truth for your Project and it's Environments.
```suggestion
    4. NOTE: `flightcontrol.json` is now the source of truth for your Project and its Environments.
```

2024-06-09 08:30 UTC, Tobbe approved these changes

2024-06-09 08:30 UTC, merged

2024-06-09 08:30 UTC, Tobbe commented
Thanks @ajoslin103 🙏