Docs: update GitHub workflow file for running tests
redwoodjs/redwood pull request #11173
Opened 2024-08-08 18:49 UTC by c-ciobanu

I tried following the guide and added the workflow to my repo but then the action failed with the following error:
```
error This project's package.json defines "packageManager": "yarn@4.1.0". However the current global version of Yarn is 1.22.22.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
Error: Process completed with exit code 1.
```
I enabled Corepack and the workflow run correctly.

Added the extra step in the docs for the people that might incur in the same issue.
Also updated the `actions/checkout` and `actions/setup-node` to v4.

2024-08-08 22:27 UTC, Josh-Walker-GM approved these changes
Looks great. I haven't tested this myself but trust your work here. The changes are consistent with what we use on the framework side of things so it all looks good.

I'm glad it worked with just this small change!

2024-08-08 22:29 UTC, Josh-Walker-GM requested changes
Oh hold on I see lines 328-335. Do you think we should update the usage there to be consistent with your change above?

2024-08-09 07:50 UTC, c-ciobanu commented
> Oh hold on I see lines 328-335. Do you think we should update the usage there to be consistent with your change above?

Oh yeah, I scrolled through it but totally didn't see it.
Updated there too.

2024-08-09 18:19 UTC, Josh-Walker-GM approved these changes
Thanks!

2024-08-09 18:19 UTC, merged