Don't create an AuthProvider if one exists
redwoodjs/redwood pull request #1251
Opened 2020-10-01 22:08 UTC by amorriscode

This PR:
- [x] Resolves #624 
- [x] Adds two basic auth generator tests

Result of command:

```bash
❯ yarn rw g auth netlify
yarn run v1.22.4
$ /Users/amorriscode/dev/example-blog/node_modules/.bin/rw g auth netlify
Existing auth provider found
✨  Done in 1.90s.
```

2020-10-02 00:17 UTC, thedavidprice requested changes
@amorriscode Thanks for getting this one going! We do indeed want to check for existing and default to _not_ overwriting. However, we also need to provide an option to override with the `--force` flag.

Take a look at how the `setup tailwind` command works here --> https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/setup/tailwind/tailwind.js

For each step in the process where a file is created or modified, there's a check if it exists. If so, it declines to run the step _unless_ `force` is passed. Example here:
https://github.com/redwoodjs/redwood/blob/66e39e67d11e44e789390aed4cae735689e5464e/packages/cli/src/commands/setup/tailwind/tailwind.js#L85-L96

Note: you don't really need to run this check for installation of packages because Yarn will handle that by default.

Does all this make sense?

2020-10-02 00:24 UTC, thedavidprice commented
@amorriscode one more FYI. A next step here after this is merged could be to move the `auth.js` command (and provider directory) to be a part of the new Setup command. Each auth provider will be a specific setup command, e.g. `yarn rw setup auth0` or `yarn rw setup netlify-auth`.

Take a look at how I deprecated the previous `rw g util tailwind` command here https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/util/tailwind and moved it here https://github.com/redwoodjs/redwood/tree/main/packages/cli/src/commands/setup/tailwind

If you do this, make sure we:
- give deprecation info in the files as well as the CLI output
- update the CLI Docs on the website (can just create an issue)
- create auth-specific names for each provider setup command (because in addition to `setup netlify-auth` we'll also eventually have `setup netlify-deploy`)

Having written this out, it might be a heavier lift than I initially thought. But just let me know either way. NO pressure!

2020-10-02 20:25 UTC, amorriscode commented
@thedavidprice would love some feedback on the handling of `--force`. The file override was already in place in the handler for the auth lib file: https://github.com/redwoodjs/redwood/blob/66e39e67d11e44e789390aed4cae735689e5464e/packages/cli/src/commands/generate/auth/auth.js#L153-L162

To handle `--force` elsewhere, I'm detecting the current `AuthProvider`, replacing its `init` code, and updating the `AuthProvider` component. Let me know what you think! It seems to work alright on my end.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/16005567/94966722-9a0a7b00-04b2-11eb-8fd9-c0680dcf9930.png">

As far as the other task goes (moving `auth.js`), I think I'll tackle that in another PR!

2020-10-03 02:02 UTC, thedavidprice requested changes
Anthony! This is looking great and I can tell you're thinking through all the changes and edge cases really well. Lot of work here.

In addition to the change request inline, there's one more thing that's not working correctly on `--force`

The section starting L225 `title: 'Adding auth config to GraphQL API...',` doesn't have any conditional logic in case of `--force`. So what happens is that you end up with a double import:
```js
// api/src/functions/graphql.js
...
import schemas from 'src/graphql/**/*.{js,ts}'
import services from 'src/services/**/*.{js,ts}'

import { getCurrentUser } from 'src/lib/auth'

import { getCurrentUser } from 'src/lib/auth.js'
import { db } from 'src/lib/db'
...
```

So in case of `force`, you might just skip this step. A better way (more aligned with the work you've been doing here) would be to check if `import { getCurrentUser } from 'src/lib/auth'` exists and act accordingly.

Lastly, I did make several code change requests based on Prettier warnings. Mostly curious as to why my VS Code settings were flagging these and why they didn't just update on save on your end. Maybe it's me?

2020-10-03 15:16 UTC, amorriscode commented
@thedavidprice can't believe I missed the GraphQL import! 😅 With the formatting, I feel like maybe my VS Code is just unhappy with so many plugins. This morning I realized there was a TypeScript/JS one that was conflicting with Prettier. I don't see any Prettier warnings on my code but at least when I run the formatter it seems to be happier now.

Might try starting fresh and seeing what happens.

2020-10-03 19:39 UTC, thedavidprice commented
All good! I'll spend some time with this on Monday in hopes of getting it merged -- but it looks great first glance. Thank you so much.

2020-10-05 04:54 UTC, thedavidprice commented on packages/cli/src/commands/generate/auth/auth.js
> +    /(import {.*} from 'src\/lib\/auth.*')/s
This is throwing an error:
```bash
object null is not iterable (cannot read property Symbol(Symbol.iterator))
```

But I manually checked logic for case true | false and it's working well.

2020-10-05 05:02 UTC, thedavidprice commented
Ok, _so close_ — just two things I found. First is the code comment about an error. Secondly, I didn't notice this before but check out these two templates files:
- Firebase: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/auth/providers/firebase.js
- magicLink: https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/auth/providers/magicLink.js

...and compare them to...

- https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/generate/auth/providers/auth0.js

It turns out the first two files are missing the three comment lines, which are needed for the `--force` to work correctly on the file `index.js`. E.g. currently if you try to re-generate auth with `-f` and `firebase`, it seems you end up with the duplicate lines in `web/index.js`. But for `netlify` or `auth0` it finds and replaces very nicely.

So want to confirm you're seeing the same behavior I'm seeing here. And, if so, it seems the easy resolution is to:
- [ ] Add the three comment lines to `auth/providers/firebase.js` and `auth/providers/magicLink.js`

Sound good?

2020-10-05 22:22 UTC, amorriscode commented
@thedavidprice I'm having trouble reproducing the issue. 😢 

Here is a screenshot after running `yarn rw g auth magicLink --force` on the example blog:
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/16005567/95138008-1c4aa780-071e-11eb-8282-46646ce573a8.png">

Here is a screenshot after running `yarn rw g auth firebase --force` on the example blog:
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/16005567/95138074-3a180c80-071e-11eb-9480-670246193d44.png">

Two things to note:
1. There is some extra whitespace I'm having trouble getting rid of that you can see in both screenshots
2. I've found that I have to relink using Redwood tools after using `--force`; the last step of the auth gen installs packages which wipes out my link meaning if I run `auth --force` commands back to back, without relinking with `rwt`, it doesn't work

Sorry I haven't been able to resolve this on my own.

2020-10-06 07:13 UTC, thedavidprice commented on packages/cli/src/commands/generate/auth/auth.js
> +    /(import {.*} from 'src\/lib\/auth.*')/s
for `.match()` "Matches a string or an object that supports being matched against, and returns an array containing the results of that search, or null if no matches are found."

So I believe what's happening in the case where project does **not** already have auth, it returns `null` and throws.

2020-10-06 07:24 UTC, thedavidprice commented
>There is some extra whitespace I'm having trouble getting rid of that you can see in both screenshots

^^ Ah, that's low priority.

>I've found that I have to relink using Redwood tools after using --force; the last step of the auth gen installs packages which wipes out my link meaning if I run auth --force commands back to back, without relinking with rwt, it doesn't work

^^ huh, that's also weird + frustrating. I've been reverting commits in my test project after each test, so maybe that's what's keeping me from having to stop, `yarn --force`, then `yarn rwt cpw ...` again.

> Sorry I haven't been able to resolve this on my own.

^^ Apology not needed. I'm here to help. And you're the one doing the work! Don't stop now.

2020-10-06 07:32 UTC, thedavidprice commented
Ok, see my new comment inline regarding the error at line 146. Once you get setup, I think you'll hammer through this to the finish line 🏁

Here's my setup and recommendations:
1. fresh installation: `yarn create redwood-app test`
2. Git init, add, and commit
3. do the setup dance: in Framework `yarn build:watch`, and in test/ project `yarn rwt cpw ../dir/to-framework`
4. **Fix Error:** try running `yarn rw g auth netlify`, which should throw.
   - do magic to resolve
5. `yarn rw g auth netlify` On success, commit.
6. Open `web/src/index.js`
7.  Run `yarn rw g auth firebase -f` --> it'll have duplications in web/src/index.js, most noticeably `<AuthProvider ...`
8. Revert file changes
9. Add those three comment lines to the firebase and magicLink files
10. Run again with -f and it works correctly with no duplications ¯\_(ツ)_/¯
11. Ship. It.

2020-10-06 13:51 UTC, amorriscode commented
Thanks for the help @thedavidprice. I still think the issue with running the command twice is that the first `yarn rw g auth netlify` replaces the CLI that is linked with `yarn rwt cpw`. I could be wrong but try this...

## Test 1 (Fails)

1. Fresh install `yarn create redwood-app test`
2. Initial commit
3. In the framework `yarn build:watch` then test project `yarn rwt cpw ../dir/to-framework`
4. `yarn rw g auth netlify` (installs npm modules) --> commit
5. `yarn rw g auth firebase -f` --> bad force
6. Revert file changes

## Test 2 (Succeeds)

1. Fresh install `yarn create redwood-app test`
2. Initial commit
3. In the framework `yarn build:watch` then test project `yarn rwt cpw ../dir/to-framework`
4. `yarn rw g auth netlify` (installs npm modules) --> commit
5. **Restart `yarn rwt cpw ../dir/to-framwork` in the test project**
6. `yarn rw g auth firebase -f` --> everything looks good!

2020-10-08 07:12 UTC, thedavidprice commented
>  I still think the issue with running the command twice is that the first yarn rw g auth netlify replaces the CLI that is linked with yarn rwt cpw

Gah, now my brain hurts! I could have sworn I check this the first go around and, therefore, assumed it was something with the regex matching (admittedly I didn't dig in to that part of the code). Makes sense that `yarn` running would bust the linking but then why... never mind. Let's get this thing merged.

Thank you and well done! 🚀

2020-10-08 07:20 UTC, thedavidprice approved these changes

2020-10-08 07:20 UTC, merged