Make ESLint configuration aware of "env."
redwoodjs/redwood pull request #1827
Opened 2021-02-21 05:05 UTC by peterp

Splits the ESLint configuration into two files:
1. "shared" that's extended by the code RedwoodJS framework, and a RedwoodJS project. It contains stylistic rules.
2. "main" that's used by a RedwoodJS project and defines rules based on the file structure.

In additional to spitting up the configuration we now set the environment that the code executes in, whereas before we set "node", "browser", and "jest" all to true, so globals like `window` would be available in every environment.

This also disables usage of `window` in the RedwoodJS framework code.

2021-02-23 03:40 UTC, thedavidprice requested changes
> **edit:** despite going one PR at a time, I might have merged in a 🐛 in main. Diagnosing now.

@peterp holy eslint refactor! Overall looking good to me. I ran some local tests:
- E2E = ✅ 
- `rw test` on the E2E project after run = ⛔
- `rw storybook` on the E2E project after run = ✅ 

## `rw test` mixed behavior
The command `yarn rw test` fails with the following error:
```bash
$ rw test    
yarn run v1.22.10
$ /private/var/folders/gj/_y54h7q11mz9rwnhn16h6yrr0000gn/T/redwood.o0cP1Pwp/node_modules/.bin/redwood test
/bin/sh: yarn: command not found
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

However, I can individually run either `rw test api` or `rw test web`. But then I run into strange test failures. E.g. for `rw test web` I'm seeing things like:
```bash
 FAIL   web  web/src/pages/AboutPage/AboutPage.test.js
  ● Test suite failed to run

Jest encountered an unexpected token
...

Details:

    /Users/price/Repos/redwoodjs-redwood/packages/structure/dist/model/RWCell.js:3
    import { withCell } from "@redwoodjs/web";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      33 | var _URL = require("../x/URL");
      34 |
    > 35 | var _RWCell = require("./RWCell");
         |               ^
      36 |
      37 | var _RWComponent = require("./RWComponent");
      38 |

      at Runtime.createScriptFromCode (../node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (../../../../../../../../Users/price/Repos/redwoodjs-redwood/packages/structure/dist/model/RWProject.js:35:15)
```

## Something off between these changes and Structure package?
I'm seeing the Structure package referenced in all the test failure errors.

And the CLI Test command does use the Structure package to determine sides. See:
https://github.com/redwoodjs/redwood/blob/53bcdb2229d526507f8f17775304eb824f285541/packages/cli/src/commands/test.js#L32

As for what could possibly be going on, I'll have to leave that answer in your hands 🤔

2021-02-23 03:43 UTC, thedavidprice commented
**Suggestion:**
We use Yargs Positional to give options in the Build command. See [code here](https://github.com/redwoodjs/redwood/blob/53bcdb2229d526507f8f17775304eb824f285541/packages/cli/src/commands/build.js#L30-L35).

I think we'd improve the Test command by doing the same [here](https://github.com/redwoodjs/redwood/blob/53bcdb2229d526507f8f17775304eb824f285541/packages/cli/src/commands/test.js#L32). We could replace it with:
```js
    .positional('side', {
      choices: getProject().sides,
      default: getProject().sides,
      description: 'Which side(s) to test',
      type: 'array',
    })
```

2021-02-23 17:17 UTC, peterp commented
@thedavidprice That seems good, but is this request related to this PR?

2021-02-24 01:38 UTC, thedavidprice approved these changes

2021-02-24 01:38 UTC, merged