Create SECURITY.md
redwoodjs/redwood pull request #1952
Opened 2021-03-10 01:21 UTC by thedavidprice

2021-03-10 08:47 UTC, Tobbe requested changes

2021-03-10 08:47 UTC, Tobbe commented on SECURITY.md
> +If you discover a potential security issue, do let us know as soon as possible. We'll work toward resolution as quickly as possible, so please provide us with a reasonable amount of time before discl
```suggestion
If you discover a potential security issue, do let us know as soon as possible. We'll work toward a resolution as quickly as possible, so please provide us with a reasonable amount of time before disclosure to the public or a third-party.
```

2021-03-10 08:47 UTC, Tobbe commented on SECURITY.md
> +Contact us at **EMAIL HERE**
Don't forget to insert actual email

2021-03-10 08:47 UTC, Tobbe commented on SECURITY.md
> +| 0.x.x   | :white_check_mark: |
I'm not sure I understand this table. What is it for? Is this how it should look?

2021-03-16 18:45 UTC, thedavidprice commented
- [ ] add redwoodjs.com/security.txt 
    - add link to Security.md
    - add email to contact us
 - [ ] add section somewhere that shows up in Search

2021-03-18 15:19 UTC, cannikin approved these changes
Other than the missing version and **EMAIL HERE** looks good to me!

2021-06-22 02:09 UTC, thedavidprice commented on SECURITY.md
> +Contact us at **EMAIL HERE**
```suggestion
Contact us at [security@redwoodjs.com](mailto:security@redwoodjs.com)
```

2021-06-22 02:12 UTC, merged