Convert CRWA seed load script to Typescript
redwoodjs/redwood pull request #2553
Opened 2021-05-19 14:39 UTC by dthyresson

This PR converts the `seed.js` Prisma load script to Typescript according to the instructions found: https://www.prisma.io/docs/guides/database/seed-database#seeding-your-database-with-typescript

It:

* renames file
* uses import rather than require
* adds dev dependencies for ts-node and @types/node
* adds additional --compiler-options to the script that Prisma uses to run the seed script

These changes do work:

![image](https://user-images.githubusercontent.com/1051633/118831992-36d92780-b88e-11eb-88a6-03442e92b10a.png)

But, I'm not certain that if:

* dev dependencies are in the right package
* if compiler options should be in tsconfig?
* should CRWA support a seed.js and seed.ts (and if so, how to install the seed file/add dependencies based on if project is typescript or not)

2021-05-19 14:50 UTC, dac09 commented
Nice DT, yeah I'm wondering the same about the dependencies. Perhaps what I would do here is have an additional step in CRWA if its a typescript project that adds tsnode as dep and the script

2021-05-19 16:00 UTC, dthyresson commented
One idea I had that I confirmed seems like it could work is to add the `api/db` path to the ts-to-js conversion script:

```
// convertTsProjectToJs in internal/devtools
export const typeScriptSourceFiles = (cwd: string) => {
  // TODO: When sides are expanded read the `api` and `web` string instead
  // of hard-coding them.
  return glob.sync('{api,web}/{src,db}/**/*.{ts,tsx}', {
    cwd,
  })
}
```

This *does* convert seed.ts to seed.js but seeding then complains:

```terminal
Running Prisma CLI:
yarn prisma db seed --preview-feature --schema "/Users/dthyresson/redwood-tests/seedtest9/api/db/schema.prisma" 

Prisma schema loaded from db/schema.prisma
Running node "db/seed.js" ...
/Users/dthyresson/redwood-tests/seedtest9/api/db/seed.js:2
import { PrismaClient } from '@prisma/client'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1172:16)
    at Module._compile (internal/modules/cjs/loader.js:1220:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Error: Command failed with exit code 1: node "db/seed.js"
error Command failed with exit code 1.
```

So, if can sort that out, then don't need any conditional logic, the TS to JS conversion will handle.

2021-05-19 16:03 UTC, dac09 commented
That import thingy happens, because the typescript file isn't preprocessed (not babel'ed). I guess internally prisma cli uses tsnode, when it sees it configured on the project.

2021-05-19 16:53 UTC, dthyresson commented
> because the typescript file isn't preprocessed (not babel'ed).

Is there a way for me to fix that?

2021-05-19 17:01 UTC, dac09 commented
Change would have to be on the prisma end I'm afraid, because they're ones invoking the seed script, not us.

2021-05-19 17:02 UTC, dthyresson commented
> Change would have to be on the prisma end I'm afraid, because they're ones invoking the seed script, not us.

Could I pre-process `seed.ts` in the `ts-to-js` script to convert?

2021-06-02 00:11 UTC, dthyresson commented on packages/create-redwood-app/src/create-redwood-app.js
> +      title: 'Updating Prisma seed file imports',
This task replaces the first 2 lines of the seed.ts with `require`s and renames the seed.ts to seed.js.

Perhaps instead can use babel?

2021-06-02 00:24 UTC, dthyresson commented
@peterp Please see the `title: 'Updating Prisma seed file imports'` task.

This simply replaces the imports for the JS version of the seed file.

Ideally, this would be transpiled to JS instead I imagine but I did not see a way for `convertTsProjectToJs` to add that api/db path.

2021-06-03 17:26 UTC, dthyresson commented
@dac09 and I paired and decided that for simplicity, clarity and future use (ie, to have specific seed examples for Typescript using actual Prisma types) it would be better to keep two separate ts and js template files and create that file as `api/db/seed` with the proper expected extension in CRWA.

2021-06-04 10:23 UTC, dac09 approved these changes
This is the simplest solution for now, and I like it! We can iterate on this as our requirements change, or as prisma updates their workflow for seeding dbs

2021-06-04 10:24 UTC, dac09 commented
Something else I would mention in the docs for this @dthyresson - if you needed more powerful seeding functions that access your services, you can always generate a script with `yarn rw g script seed` and `yarn rw exec seed`

2021-06-08 11:18 UTC, peterp requested changes
I actually don't think this is the correct approach because using `seed.ts` in this way will diverge the way we handle transpilation into two paths: the Redwood way (babel), and then a completely separate way (ts-node), but without any of our transformations. Sorry @dthyresson!

This may be problematic if people import other files in `src` and expect it to behave the same. I think an approach could be to overwrite the `prisma db seed` command and wire it up with our own babel transpilation instead of using `ts-node`

2021-06-08 11:59 UTC, dthyresson commented
> I think an approach could be to overwrite the `prisma db seed` command and wire it up with our own babel transpilation instead of using `ts-node`

@peterp Prisma seed is still a preview feature. Should we get their input before changing their command -- which does require ts-node as per https://www.prisma.io/docs/guides/database/seed-database#requirements-for-seeding-with-typescript-or-javascript

2021-06-08 12:34 UTC, peterp commented
@dthyresson I think that's a good idea - we could suggest to them that we want to use our own transpilation - perhaps there's a way that they could allow us to specify a command, or a pre-transpile function.

2021-06-29 14:42 UTC, dthyresson commented
Assigning to @peterp per standup 6/28 as has ideas to transpile vs swap out.

2021-06-29 18:05 UTC, peterp commented
Ok, I'm going to overwrite the `yarn rw prisma db seed` command so that it uses our babel scripts instead of Prisma's implementation. Does that sound like a reasonable to you @dthyresson ?

2021-06-29 18:11 UTC, dthyresson commented
> Does that sound like a reasonable to you @dthyresson ?

Yes, but may need to override `migrate reset` as well since it calls their seed command as well.

2021-06-30 12:04 UTC, Jolg42 commented
Hi @peterp & @dthyresson!

So you could use one of these solutions to make seed execute what you want here:

1 - Add the the package.json a `ts-node` script that `db seed` will check and use if defined
```
"scripts": {
 "ts-node": "ts-node --compiler-options '{\\\"module\\\":\\\"commonjs\\\"}'"
},
```
https://www.prisma.io/docs/reference/api-reference/command-reference#db-seed-preview

I can see how this can be confusing (naming it `ts-node` but it can actually be any command), we'll think about this and see what we can improve.

2 - Creating a `seed.sh` bash script where you could do anything you want.
https://www.prisma.io/docs/guides/database/seed-database#seeding-your-database-with-a-bash-script

2021-07-01 08:56 UTC, peterp commented
@Jolg42 Awesome, thanks!

2021-07-06 21:21 UTC, peterp commented
@dthyresson What if we provided a default `seed.sh` script which called `yarn babel-node ./seed.ts`? I think that may use our babel configurations and solve most of our problems.

2021-07-06 21:22 UTC, peterp reviewed
Based on an earlier discussion: We're either going to leave this as an ordinary JS file, or we're going to try one last thing with the seed.sh file and `yarn babel-node`

2021-07-21 22:19 UTC, thedavidprice commented
@dthyresson nudging you on this one — we decided to _not_ support TS, correct? If so, what are the next steps with this one?

2021-07-21 22:25 UTC, dthyresson commented
> @dthyresson nudging you on this one — we decided to _not_ support TS, correct? If so, what are the next steps with this one?

@thedavidprice I think based on our other discussions, we said we're ok with this seed file being simply a .js file. 

Therefore, I think we can close out this PR and not merge these changes in.

We can revisit post 1.0 when/if Prisma changes how their seed command works (as is still officially a preview feature).

A good next step would be to work with them to 

1. let the ts version of the seed file run without the necessary
```
    "ts-node": "ts-node --compiler-options '{\"module\":\"CommonJS\"}'"
```

2. maybe let their seed and or db reset command run a user-defined script that Redwood can run it its way

2021-07-21 23:30 UTC, thedavidprice commented
@dthyresson Got it. I'll let you do the closing!

Should we add a comment in the template file that TS is not supported... and/or document this somewhere?

2021-07-22 16:03 UTC, dthyresson commented
> @dthyresson Got it. I'll let you do the closing!
> 
> Should we add a comment in the template file that TS is not supported... and/or document this somewhere?

@thedavidprice Have added a message in the seed cli command docs here: https://github.com/redwoodjs/redwoodjs.com/pull/754

Closing.

2021-07-22 16:03 UTC, closed without merging