Docs Update - Eslint Config README w/example override
redwoodjs/redwood pull request #3029
Opened 2021-07-12 16:01 UTC by webstackdev

Added info and example on overriding ESLint config, in response to Forum question [#2275](https://community.redwoodjs.com/t/redwood-eslint-config-modifications/2275)

2021-07-13 23:16 UTC, jtoar requested changes
@webstackdev this is fantastic, thank you so much! I suggested a few changes for clarity, let me know what you think

2021-07-13 23:16 UTC, jtoar commented on packages/eslint-config/README.md
> +// redwood/package.json
- just a little clearer
```suggestion
// redwood-app/package.json
```

2021-07-13 23:16 UTC, jtoar commented on packages/eslint-config/README.md
> +This package has no dependencies on other Redwood Framework packages. To contribute, you should be familiar with the ESLint package. Keep in mind that any rules added should not conflict with code fo
- sounded a little awkward
```suggestion
This package doesn't depend on other Redwood Framework packages. To contribute, you should be familiar with the ESLint package. Keep in mind that any rules added should not conflict with code formatting tools (e.g. [Prettier](https://prettier.io/docs/en/integrating-with-linters.html)).
```

2021-07-13 23:16 UTC, jtoar commented on packages/eslint-config/README.md
> +// redwood/.eslintrc.js
- just a little clearer
```suggestion
// redwood-app/.eslintrc.js
```

2021-07-13 23:16 UTC, jtoar commented on packages/eslint-config/README.md
> +By default, ESLint will recurse through all project directories looking for configuration files and directives, and overriding those specified in multiple places according to a prioritization formula
- tense maybe?
```suggestion
By default, ESLint will recurse through all project directories looking for configuration files and directives, and override those specified in multiple places according to a prioritization formula. The `root` directive tells ESLint to stop searching for configuration lower in the tree at the file this directive is encountered.
```

2021-07-18 15:14 UTC, webstackdev commented
@jtoar thanks, your suggests are added to the PR

2021-07-18 19:46 UTC, jtoar approved these changes

2021-07-18 19:46 UTC, merged