Storybook: Add support for a custom `manager.js`
redwoodjs/redwood pull request #3688
Opened 2021-11-03 06:51 UTC by realStandal

Howdy!

I desired the ability to [theme my project's Storybook](https://storybook.js.org/docs/react/configure/theming), so I made it so.

This PR adds support for defining a project-level `manager.js` file, which can be used to customize Storybook's UI.

> Sorry for not running the lint command before opening a PR - the command kept failing. Going to look into it to see if it's something I need to open an issue for. Yay Windows...

> Same deal for tests, I don't *think* my changes affect any tests, but some were failing  that were completely unrelated. Going to see how GitHub runs them.

> I'm going to throw types in too, type-checking did *not* want to work - I think it may be the same issue as testing.

## Explanation

This PR includes the following:

* Adds a `storybookManagerConfig` path to `getPaths().web`
  * The path in a project is expected to be: `web/config/storybook.manager.js`
* Adds a `--no-manager-cache` option to `yarn rw storybook`
* Adds an (empty) example manager-file alongside the preview's existing one.
* Adds a `managerWebpack` configuration to the framework's `main.js` file.
  * Storybook's UI uses a separate Webpack configuration from its preview, worth noting.
  * A project's `manager.js` file is aliased and merged, done identically to `preview.js`.
  * If a project does not have a `storybook.manager.js` file, the example is loaded instead.

## Examples

A few examples to show off what I was after with these changes (please excuse any [CRUD-ness](https://i.kym-cdn.com/entries/icons/original/000/014/959/Screenshot_116.png)).

<details>
  <summary>Storybook's default "light" theme</summary>

  ![Storybook-manager-SBBranding](https://user-images.githubusercontent.com/25166787/140015537-ccb79cc3-3c30-40a0-b987-1e4a90000935.png)
</details>

<details>
  <summary>RedwoodJS-inspired theme</summary>

  ![Storybook-manager-RWBranding](https://user-images.githubusercontent.com/25166787/140015604-a0107bf8-fc8a-4111-95d8-8ad37b65ae6f.png) 
</details>

<details>
  <summary>Branded theme</summary>

  ![Storybook-manager-LTBranding](https://user-images.githubusercontent.com/25166787/140015650-6281e457-205f-4f1c-b032-463979cfa699.png)  
</details>

## Request for Comment

I'd greatly appreciate some feedback on this/these ideas, or a big "yeah, let's not do that".

### Caching

I ran into an issue where, while testing my changes, Storybook preferred a cached `storybook.manager.js` file over one I had made changes to. This is the reason for adding `--no-manager-cache`: I think Storybook gets confused that the manager it's dealing with is the framework's, not the project's - it indirectly gets the project's.

I would greatly appreciate some direction on whether or not this is acceptable, or if there's something I can do to make sure Storybook picks up project-level changes.

### First-class support for theming

My `manager.example.js` follows suit with the existing `preview.example.js`: It's an empty file with instructions on how one can go about customizing their project's implementation of Storybook.

By default, it makes zero changes to Storybook without the user explicitly doing something. More-over, to actually theme Storybook, you need to install additional dependencies (which I highlight in the example, and will include in the docs). Then just to hit it home: all changes are done at the project-level, the framework just allows for the customizations to take place.

This brings me to my question(s): Should theming Storybook be supported out-of-the-box? Is it worth having a default, Redwood-branded theme? Should I consolidate this idea into a larger "Storybook starter pack" PR? I.e., add support for some of Storybook's more useful plugins:

* [@storybook/addon-essentials](https://storybook.js.org/docs/react/essentials/introduction)
* [@storybook/addons](https://www.npmjs.com/package/@storybook/addons)
* [@storybook/theming](https://www.npmjs.com/package/@storybook/theming)
* [@storybook/addon-graphql](https://www.npmjs.com/package/@storybook/addon-graphql)
* [storybook-addon-themes](https://storybook.js.org/addons/storybook-addon-themes)
* ...

---

I can start on a documentation PR soon as it appears this has a green-light :)

2021-11-03 23:04 UTC, thedavidprice commented
@realStandal I'm on it! At a glance this looks very interesting and I'll work to get in a full review + reply by end of this week.

Thank you!

2021-11-20 01:29 UTC, jtoar requested changes
Hey @realStandal this is awesome! That redwood themed example you showed looks legit. Had one suggestion for you about the CLI flag you introduced, but other than that looks great.

2021-11-20 01:29 UTC, jtoar commented on packages/cli/src/commands/storybook.js
> +    })
Let's make this positive and then just flip it (easier to read). Also yargs automatically generates negatives for us, so doing it this way gives us a generated flag, `--no-manager-cache` with the value false.
```suggestion
    .option('manager-cache', {
      describe:
        'Cache the manager UI. Disable this when your making changes to `storybook.manager.js`.',
      type: 'boolean',
      default: true,
    })
```

2021-11-20 01:29 UTC, jtoar commented on packages/cli/src/commands/storybook.js
> +  noManagerCache,
- continued from first suggestion
```suggestion
  managerCache,
```

2021-11-20 01:29 UTC, jtoar commented on packages/cli/src/commands/storybook.js
> +      noManagerCache && '--no-manager-cache',
- continued from first suggestion
```suggestion
      !managerCache && '--no-manager-cache',
```

2021-11-20 01:56 UTC, realStandal commented
Thank you for taking a look and the pointers @jtoar!

2021-11-20 02:00 UTC, jtoar commented on packages/cli/src/commands/storybook.js
> +        'Cache the manager UI. Disable this when you're making changes to `storybook.manager.js`.',
Ah this is my bad; I should've suggested double quotes (maybe?)
```suggestion
        "Cache the manager UI. Disable this when you're making changes to `storybook.manager.js`.",
```

2021-11-20 02:38 UTC, merged