Add errorCode as prop to Failure component
redwoodjs/redwood pull request #3721
Opened 2021-11-11 21:33 UTC by simoncrypta

This adds `errorCode` as prop for Failure in cells. 
You can get the error code with `error.graphQLErrors[0].extensions.code`, but it gives a TS error, and I think we should make it easier to have access. 

Error code can be useful for translation or conditional render. 

```tsx
export const Failure = ({ error, errorCode }: CellFailureProps) => {
  const { t } = useTranslation()
  return (
    <div style={{ color: 'red' }}>
      Error: {error.message} - Code: {errorCode} - {t(`error.${errorCode}`)} -
      {errorCode === 'NO_CONFIG' ? <h1> NO_CONFIG </h1> : <h1> ERROR </h1>}
    </div>
  )
}
```

Can it be a good idea or not to add it on the cell template generator?

Also, I first think about using something like `error.code`, but this will add complexity for TS, and It's better to keep the `ApolloError` as is it.

2021-11-11 21:52 UTC, simoncrypta commented
I will write a test for this

2021-11-11 22:34 UTC, Tobbe commented
> Can it be a good idea or not to add it on the cell template generator?

Easier access to the error code sounds great! Especially for translation support! But I don't think we should add it to the template. I think it's better to try to keep the templates small and simple 🙂  But an example in some kind of documentation somewhere would be great 📖

2021-11-11 22:51 UTC, dac09 commented
I think this is excellent, and I'd totally add this to the default generator too! 

A good example of wanting to use the error code apart from translations is exception tracking + prompting for higher privileges / signing out of auth.

2021-11-11 23:07 UTC, dthyresson commented
I do want to double check with the Guild about the use of codes in GraphQL errors. I have a vague recollection of them mentioning that Apollo’s use of codes was non-standard. Let me check with them about how client side translation of codes is commonly done w/ respect to specific errors  raised api/GraphQL side.

2021-11-15 15:29 UTC, dthyresson commented
@simoncrypta there are some build/test errors in CI to resolve. Thanks!

2021-11-15 15:32 UTC, dthyresson commented
> I do want to double check with the Guild about the use of codes in GraphQL errors.

Had the conversation and a new way of error handling in GraphQL was introduced -- errors as part of the schema and returning the the results .... not in the extensions or error section.

These would be typed errors as part of the schema:

```
interface Error {
  message: String!
}

type Query {
  operation: OperationResult!
}

type OperationError implements Error {
  message: String!
  operationSpecificProperty: String!
}

type OperationSuccess {
  yee: String!
}

union OperationResult = OperationError | OperationSuccess
```

But this idea is too big for v1.0 but should revisit perhaps in 2.0.

2021-11-15 15:33 UTC, dthyresson requested changes
Please check the CI errors, thanks!

2021-11-15 17:25 UTC, simoncrypta commented on packages/web/src/components/createCell.tsx
> +    errorCode: string
I think noting inside `extensions` is guaranteed. So yes, I need to make it optional. Also, for this reason, the CI don't pass.

2021-11-16 13:08 UTC, dac09 commented on packages/web/src/components/createCell.tsx
> +                  errorCode={error.graphQLErrors[0]?.extensions?.code}
(this will fix your test failing)

2021-11-16 14:40 UTC, simoncrypta commented on packages/web/src/components/createCell.tsx
> +                  errorCode={error.graphQLErrors[0]?.extensions?.code}
Oh, that why! I didn't know this trick, thanks!

2021-11-16 15:30 UTC, dac09 commented on packages/web/src/components/createCell.tsx
> +                  /**
I'm not 100% sure though..

2021-11-16 15:43 UTC, simoncrypta commented on packages/web/src/components/createCell.tsx
> +                  /**
Honestly, I never wrote JSdocs on JSX/TSX, so I will do my research ;)

2021-11-16 15:55 UTC, simoncrypta commented on packages/web/src/components/createCell.tsx
> +                  /**
On HOC the only place that seem to work for JSDoc is over the export function.

2021-11-18 19:19 UTC, simoncrypta commented on packages/web/src/components/createCell.tsx
> +                  /**
@dac09 I let you decide where you want the JSDoc,  the export function don't seem to be a good idea since we don't know which component will render.

2021-11-19 13:52 UTC, dac09 commented on packages/web/src/components/createCell.tsx
> +                  /**
Yeah no worries @simoncrypta - was just hoping it would be there. Might have been helpful, but was a nice-to-have anyway!

2021-11-19 13:54 UTC, dac09 approved these changes
@simoncrypta nice one! Approving... but wondering if you would humour me and change your test case to not use "INTERNAL_SERVER_ERROR" maybe to something very obviously setup by your test case e.g. "SIMON_SAYS_NO"

The reason I prefer this (I usually use "bazinga"), is to rule out any possibility that a legit error is coming through, and our test case isn't really proving the point!

2021-11-19 15:55 UTC, simoncrypta commented
Thanks, @dac09 ! I wonder if we should link the issue #3069 with this PR ?

2021-11-19 15:56 UTC, dac09 commented
> Thanks, @dac09 ! I wonder if we should link the issue #3069 with this PR ?

Simon this definitely goes a long way in reducing the pain, but I don't think it will still solve getting the network code (unless I'm mistaken?). Don't think we should close that issue.

2021-11-19 16:16 UTC, simoncrypta commented
> Simon this definitely goes a long way in reducing the pain, but I don't think it will still solve getting the network code (unless I'm mistaken?). Don't think we should close that issue.

The real network code is almost always 200 because GraphQL, but we can access to the GraphQL network error. On the Apollo Client Doc, it said : 

> When a network error occurs, Apollo Client adds it to the error.networkError field returned by your useQuery call (or whichever operation hook you used).

And also I don't know who [Link Error](https://www.apollographql.com/docs/react/api/link/apollo-link-error/) can be useful for us.

We can keep this discussion for another PR.  😜

2021-11-19 16:24 UTC, merged