Issues/3991
redwoodjs/redwood pull request #4218
Opened 2022-01-20 05:35 UTC by refactor-this

**Added a comment to all generated test files:**
`// Generated boilerplate tests do not account for all circumstances
// and can fail without adjustments, e.g. Float and DateTime types.
//           Please refer to the RedwoodJS Testing Docs:
// https://redwoodjs.com/docs/testing#jest-expect-type-considerations
`
This should make it easier for users to debug type issues such as #3601 

Let me know if anything else should be added here @thedavidprice. Thanks!

2022-01-24 06:13 UTC, thedavidprice requested changes
@refactor-this Thanks again for moving this one forward! 

I now realize in the original issue that I did not specify _which_ test template this applies to (which was the Cell tests). You made a good judgment call applying it to all. However, this message isn't universal. But you got me thinking because each type of test template has a related Testing doc section, which it would be very helpful to link.

The message you created does apply to both of these types, which also have corresponding sections:
1. Cell tests (https://redwoodjs.com/docs/testing#testing-cells)
2. Service test (https://redwoodjs.com/docs/testing#testing-services)

In addition to only using the current copy for Cell and Service templates, what do you think about adding the respective section link as well?

For the others, we don't need the warning or link to the specific section. It would be very helpful though to link to the Testing doc in general. Could you take a stab at a concise message about Testing doc that includes a link? This will apply to:
1. component (https://redwoodjs.com/docs/testing#testing-components)
2. function (https://redwoodjs.com/docs/testing#testing-functions)
3. layout (https://redwoodjs.com/docs/testing#testing-pages-layouts)
4. page (https://redwoodjs.com/docs/testing#testing-pages-layouts)

2022-01-24 06:16 UTC, thedavidprice commented
FYI: The CI is failing because the test snapshots need to be updated. See the failing test here:
- https://github.com/redwoodjs/redwood/runs/4903907237?check_suite_focus=true#step:11:2529

Which included the instruction about how to update locally (screenshot):
<img width="998" alt="Screen Shot 2022-01-23 at 10 14 34 PM" src="https://user-images.githubusercontent.com/2951/150731560-82025574-47d9-4afa-b6e9-fef744e2ec97.png">

2022-01-24 07:16 UTC, refactor-this commented
@thedavidprice Alrighty, I went through and updated the links and text along with the snapshots 🙌

2022-02-01 02:10 UTC, thedavidprice commented on packages/cli/src/commands/generate/cell/templates/test.js.template
> +//        https://redwoodjs.com/docs/testing#testing-cells
```suggestion
//        https://redwoodjs.com/docs/testing#testing-cells
// https://redwoodjs.com/docs/testing#jest-expect-type-considerations
```

2022-02-01 02:15 UTC, thedavidprice commented on packages/cli/src/commands/generate/component/templates/test.tsx.template
> +//  Please refer to the RedwoodJS Testing Docs for any issues:
```suggestion
// Improve this test with help from the Redwood Testing Doc:
```

2022-02-01 02:15 UTC, thedavidprice commented on packages/cli/src/commands/generate/function/__tests__/__snapshots__/function.test.ts.snap
> +//  Please refer to the RedwoodJS Testing Docs for any issues:
```suggestion
//   Improve this test with help from the Redwood Testing Doc:
```

2022-02-01 02:16 UTC, thedavidprice commented on packages/cli/src/commands/generate/function/templates/test.ts.template
> +//  Please refer to the RedwoodJS Testing Docs for any issues:
```suggestion
//   Improve this test with help from the Redwood Testing Doc:
```

2022-02-01 02:16 UTC, thedavidprice commented on packages/cli/src/commands/generate/layout/__tests__/__snapshots__/layout.test.ts.snap
> +//  Please refer to the RedwoodJS Testing Docs for any issues:
```suggestion
//   Improve this test with help from the Redwood Testing Doc:
```

2022-02-01 02:17 UTC, thedavidprice commented on packages/cli/src/commands/generate/layout/templates/test.tsx.template
> +//  Please refer to the RedwoodJS Testing Docs for any issues:
```suggestion
//   Improve this test with help from the Redwood Testing Doc:
```

2022-02-01 02:17 UTC, thedavidprice commented on packages/cli/src/commands/generate/page/templates/test.tsx.template
> +//  Please refer to the RedwoodJS Testing Docs for any issues:
```suggestion
//   Improve this test with help from the Redwood Testing Doc:
```

2022-02-01 02:19 UTC, thedavidprice commented on packages/cli/src/commands/generate/service/templates/test.ts.template
> +//       https://redwoodjs.com/docs/testing#testing-services
```suggestion
//       https://redwoodjs.com/docs/testing#testing-services
// https://redwoodjs.com/docs/testing#jest-expect-type-considerations
```

2022-02-01 02:23 UTC, thedavidprice approved these changes
Thank you @refactor-this (especially for being patient with me).

I wanted to make sure this is included in the release out tomorrow. Went ahead an committed tweaks I had and then updated snapshot.

Thank you so much! It's little things like this that are big wins for DX 🚀

2022-02-01 02:37 UTC, merged

2022-02-01 02:51 UTC, refactor-this commented
> Thank you @refactor-this (especially for being patient with me).
> 
> I wanted to make sure this is included in the release out tomorrow. Went ahead an committed tweaks I had and then updated snapshot.
> 
> Thank you so much! It's little things like this that are big wins for DX 🚀

Awesome!!! It's my first contribution and I am very excited to have helped especially with a project I'm using 😄