Webhook verifiers: Add base64 version
redwoodjs/redwood pull request #4598
Opened 2022-02-28 01:07 UTC by Tobbe

I wasn't possible to verify clerk webhooks, so I added a new verifier with support for those (and others that does base64 encoded buffers instead of strings)

https://docs.svix.com/receiving/verifying-payloads/how-manual

Their implementation: https://github.com/svix/svix-webhooks/blob/7f0ca5a4010ed6ace4a45ebb4accad45abe3a3fc/javascript/src/index.ts#L538

2022-02-28 01:10 UTC, Tobbe commented on packages/api/src/auth/verifiers/common.ts
> + * @param {(signature: string) => string} signatureTransformer - Optional
If we go ahead with this PR I'll add this to other relevant verifiers too

2022-02-28 01:11 UTC, Tobbe commented on packages/api/src/auth/verifiers/base64Sha256Verifier.ts
> +const base64Sha256Verifier = (
A similar base64 verifier could be added for sha1 as well

2022-02-28 15:15 UTC, dthyresson requested changes
Chatted with @Tobbe and looks good. While my first thought that this was similar to the Sha256 and also the TimestampVerifier, I was hoping for some reuse but as T found out too it wasn't that straightforward and made them too complicated. So this "svix"-like format is just different enough to need its own.

Few requests:

* do we name this SvixVerifier ?
* let's add the timestamp tolerance and verification to prevent replays

Thanks!

2022-02-28 15:24 UTC, dthyresson commented
Will also need to add this verifier example to the Webhook docs and use Clerk as the main use case and example.

2022-02-28 18:51 UTC, dthyresson approved these changes
LGTM. Approved

2022-02-28 18:52 UTC, dthyresson commented
Oh wait. Still need the timestamp check right?

2022-02-28 18:59 UTC, Tobbe commented
I was going to do that in a separate PR. But refactoring another thing in this PR atm, so let's hold for a little bit

2022-02-28 19:12 UTC, dthyresson commented
> I was going to do that in a separate PR. But refactoring another thing in this PR atm, so let's hold for a little bit

OK, thanks! Mention me when ready for a view or convert to draft and I'll wait for a ping.

2022-02-28 19:33 UTC, Tobbe commented
@dthyresson Ready

2022-02-28 19:34 UTC, Tobbe commented
Started working on docs over here: https://github.com/redwoodjs/redwoodjs.com/pull/982

2022-02-28 21:39 UTC, thedavidprice commented
Possible this is a legitimate test failure?
- https://github.com/redwoodjs/redwood/runs/5366219226?check_suite_focus=true#step:11:15

2022-03-01 06:02 UTC, Tobbe commented
> Possible this is a legitimate test failure?
> 
> * [redwoodjs/redwood/runs/5366219226?check_suite_focus=true#step:11:15](https://github.com/redwoodjs/redwood/runs/5366219226?check_suite_focus=true#step:11:15)

I don't think so. It was all green here, before rebasing the code on top of `main`
![image](https://user-images.githubusercontent.com/30793/156113825-150e7257-2565-4a83-ad68-2947fc4b755d.png)

It has always been green locally

And now it's all green here again

![image](https://user-images.githubusercontent.com/30793/156113877-8664218f-cc04-4c6e-8f12-7c022a4a877c.png)

2022-03-01 12:56 UTC, merged