Use GraphQL Yoga
redwoodjs/redwood pull request #4712
Opened 2022-03-10 14:00 UTC by ardatan

Hi!
As we discussed recently. We decided to create this PR to migrate your GraphQL Server implementation to GraphQL Yoga.
GraphQL Yoga is platform agnostic GraphQL Server for JavaScript environment that follows Web standards and supports GraphQL-over-HTTP spec together with GraphQL Multipart spec, defer/stream and SSE subscriptions.
https://graphql-yoga.com/
Thanks to Yoga, you don't need any extra configuration and code for Envelop integration, handling and parsing requests, CORS and healthchecks.
Also we saw that you're using node-fetch already for polyfilling Node and abstracting some HTTP stuff. This PR replaces it with cross-undici-fetch which is a smart ponyfill library like node-fetch but chooses the best fetch implementation according to your Node version etc(node-fetch for v14,undici for v16, native fetch for v17 etc).

As far as I see, there is no change in the user facing API (not sure if onHealthCheck is something for users) so in the docs.

We believe you can leverage more from Fetch API like we do in GraphQL Yoga so GraphQL Yoga can have tighter integration. We'd appreciate your feedback. Thanks!

2022-03-15 16:04 UTC, ardatan commented on packages/api/src/cors.ts
> +      const eventHeaders = new Headers(request.headers as HeadersInit)
No it is not typo. Request.headers can be an object map with the string arrays as values or Headers as well.

2022-03-15 16:07 UTC, dac09 commented on packages/api/src/cors.ts
> +      const eventHeaders = new Headers(request.headers as HeadersInit)
Oh but where does it come from? Just available globally?

2022-03-15 16:12 UTC, dac09 commented
@ardatan thank you for this and the crazy quick turn around. The Guild never fails to impress me ♥️

2022-03-15 16:31 UTC, ardatan commented on packages/api/src/cors.ts
> +      const eventHeaders = new Headers(request.headers as HeadersInit)
Yes it is a globally available type

2022-03-15 17:12 UTC, thedavidprice commented on .github/renovate.json
>      "pascalcase",
Ah, my mistake here. Searched through the PR and saw node-fetch removed everywhere. I also removed @types/node-fetch and removed both from renovate blocklist

2022-03-15 22:17 UTC, thedavidprice commented
Updated from main to include new CI Auth Smoke Tests via #4673

2022-03-17 16:20 UTC, dthyresson requested changes
Had one question about the use of `localhost` in the `hanlderFn`.

2022-03-17 16:20 UTC, dthyresson commented on packages/graphql-server/src/functions/graphql.ts
> +    const request = new Request(`http://localhost${event.path}`, {
@ardatan and @dac09 is `localhost` here expected?

2022-03-21 14:58 UTC, dthyresson commented
@dac09 and @ardatan I resolved the conflicts an updated the branch. I still think we have a few questions about use of localhost and perhaps CORS to think about before merge and testing.

2022-03-21 14:59 UTC, dthyresson commented
I just realized I may have added back node-fetch as part of conflict resolution

2022-03-21 15:03 UTC, ardatan commented on packages/graphql-server/src/functions/graphql.ts
> +      return {}
Actually Envelop isn't responsible of CORS. So not sure if I understood what you mean there :) Yoga handles CORS and health check out of box. `corsOptions` is what Yoga generates by using `cors` object provided in the `createGraphQLHandler`'s parameters.

2022-03-21 15:05 UTC, ardatan commented on packages/graphql-server/src/functions/graphql.ts
> +    const request = new Request(`http://localhost${event.path}`, {
`localhost` is just a dummy value there. We create a Request object for GraphQL Yoga then Yoga processes it and returns `Response`.

2022-03-21 15:11 UTC, ardatan commented on packages/graphql-server/src/functions/graphql.ts
> +      return {}
Oh I just saw that I didn't use the same logic there. I'm fixing it now.

2022-03-21 16:03 UTC, ardatan commented on packages/graphql-server/src/functions/graphql.ts
> +      return {}
Oh my bad :)

2022-03-21 16:56 UTC, dac09 commented on packages/graphql-server/src/functions/graphql.ts
> +    graphiql: false,
Yup yup... just trying it out now. Let me push up my changes in 2 mins!

2022-03-21 16:57 UTC, dthyresson commented on packages/graphql-server/src/functions/graphql.ts
> +    graphiql: false,
FYI old code was:

```ts
    if (isDevEnv && shouldRenderGraphiQL(request)) {
      return {
        body: renderPlaygroundPage({
          endpoint: graphiQLEndpoint || '/graphql',
        }),
        statusCode: 200,
        headers: {
          'Content-Type': 'text/html',
          ...corsHeaders,
        },
      }
    }
```

So, we made sure that we were in Dev and also that for headers got passed

2022-03-21 16:58 UTC, ardatan commented on packages/graphql-server/src/functions/graphql.ts
> +    graphiql: false,
Why do we need CORS headers for GraphiQL?

2022-03-21 17:41 UTC, dthyresson approved these changes

2022-03-21 18:04 UTC, dthyresson commented
GraphQL Playground running on GitPod

![image](https://user-images.githubusercontent.com/1051633/159336154-caa8e1d6-5495-43e1-adec-b5ca941fadb1.png)

2022-03-21 18:04 UTC, dac09 approved these changes

2022-03-21 18:09 UTC, merged

2022-04-02 21:54 UTC, borekb commented
Just to confirm, this entirely replaces Helix, right? Helix is still mentioned in places like [README](https://github.com/redwoodjs/redwood/blob/30e9e6305061bbbb24f980811b5d448eca0d8b77/README.md#technologies) and a [few others](https://cs.github.com/redwoodjs/redwood?q=helix) but that might just be something that yet needs updating.

BTW were there any issues with Helix or is Yoga just easier / more convenient to use? We'll be doing a similar decision soon 😊.

2022-04-02 22:25 UTC, dthyresson commented
Hi @borekb 
> Just to confirm, this entirely replaces Helix, right? 

Correct, the RedwoodJS GraphQL Server uses Yoga 2.0 now instead of Helix.

Helix is still mentioned in places like [README](https://github.com/redwoodjs/redwood/blob/30e9e6305061bbbb24f980811b5d448eca0d8b77/README.md#technologies) and a [few others](https://cs.github.com/redwoodjs/redwood?q=helix) but that might just be something that yet needs updating.

Thanks! We do need to clean up those mentions. Appreciate you finding them.

> BTW were there any issues with Helix or is Yoga just easier / more convenient to use? 

No, no issues with Helix. RedwoodJS decided to use Yoga based on the collaboration with the Guild.

While @dotansimha can explain more, in short, (my take) Yoga takes the "best parts" of Helix, adds in what the Guild had learned from their customers using it in production, better integrates their envelop plugin system, and is now a project that they can maintain, support and improve faster and more easily than Helix (which is maintained by another party).
 
> We'll be doing a similar decision soon

Sounds great. The transition for Redwood was really smooth.