chore(tutorial): update routing section about splash screen
redwoodjs/redwood pull request #4924
Opened 2022-03-25 12:47 UTC by ctison

### Summary

Issue: #4910

Update the Tutorial Chapter 1 [`Our First Page`][1]'s routing section about the splash screen.

[Preview](https://github.com/ctison/redwood/blob/chore/tutorial/routing-splash-screen/docs/docs/tutorial/chapter1/first-page.md)

[1]: https://redwoodjs.com/docs/tutorial/chapter1/first-page

2022-03-25 17:35 UTC, cannikin requested changes

2022-03-25 17:35 UTC, cannikin commented on docs/docs/tutorial/chapter1/first-page.md
> +As long as you have a Home route with path `/`, you'll never see the initial Redwood splash screen again.
```suggestion
As long as you have a route with path `/`, you'll never see the initial Redwood splash screen again.
```

Saying "Home" implies that the route has to be named that or something, but really any route at `/` will take over the splash screen.

2022-03-26 16:14 UTC, thedavidprice approved these changes

2022-03-26 16:14 UTC, thedavidprice commented
Thanks so much @ctison Welcome to Redwood 🚀

2022-03-26 16:15 UTC, merged