Added draft notes about pm2
redwoodjs/redwood pull request #5219
Opened 2022-04-17 15:11 UTC by zpeters

started on a draft of additional pm2 direction for review.

Still working on the global pm2 switch.  Will add additional detail when that is ready.

2022-04-17 16:53 UTC, jtoar commented
@cannikin May have request a review from you too soon. @zpeters let us know when it's ready—thanks for taking this on!

2022-04-22 01:16 UTC, zpeters commented
Added notes around the global pm2 options.  I don't know if im fully happy with the wording.  Open to suggestions!

2022-04-22 15:24 UTC, cannikin requested changes

2022-04-22 15:24 UTC, cannikin commented on docs/docs/deploy/baremetal.md
> +If you choose to run pm2 'globally' you would need to follow the pm2 projects instructions for setting this up.  https://pm2.keymetrics.io/docs/usage/quick-start/.  Typically this is `npm install pm2
```suggestion
If you choose to run pm2 'globally' you would need to follow the pm2 project's instructions for setting this up.  https://pm2.keymetrics.io/docs/usage/quick-start/.  Typically this is `npm install pm2@latest -g` as root.
```

2022-04-22 15:25 UTC, cannikin commented
We can keep the Self-Hosting doc for now, but we should probably deprecate that doc and refer people to the Docs > Deployment > Baremetal docs going forward.

2022-04-25 19:12 UTC, cannikin commented
I've done a bunch of updates to this doc in https://github.com/redwoodjs/redwood/pull/5282 which covers the discussion of a global install, thanks!

2022-04-25 19:12 UTC, closed without merging