feat: add GenerateGraphiQLHeaders as new param in createGraphQLHandler
redwoodjs/redwood pull request #5512
Opened 2022-05-11 17:35 UTC by alicelovescake

Draft PR

- Fixes #5007

2022-05-12 13:18 UTC, dthyresson commented
I also noticed this issue which could be related?

https://github.com/dotansimha/graphql-yoga/issues/1163

2022-05-12 13:18 UTC, dthyresson requested changes
We'll pair soon to go over how we might mock the credentials per auth provider

2022-06-26 03:14 UTC, alicelovescake commented on packages/api/src/functions/dbAuth/shared.ts
> +// Checks for cookie in headers only in dev when user has generated graphiql headers
It is hard to tell but in the `packages/graphql-server/src/functions/graphql.ts`, the graphiql function is only inserted when `isDevEnv`,  so to extract the cookie when we insert the header into the gql query, it only works by checking the extensions.

To make it more explicit, I added a `isDevEnv` check here in the extract cookie function directly.

2022-07-03 21:07 UTC, dthyresson commented
@alicelovescake I tried to resolve conflicts and gets tests to pass. Can your review so we can merge?

Note: I had to add a null check the in the shared code for dbAuth when checking cookies.

2022-07-03 22:44 UTC, alicelovescake reviewed
@dthyresson Good catch on the checking for null case when checking the session cookie. I just changed the cookie from graphiql header to return `undefined` so we don't have to do the extra null check. Otherwise, I think we are good to merge

```
const cookieFromGraphiqlHeader =
    process.env.NODE_ENV === 'development'
      ? JSON.parse(event.body ?? '{}').extensions.headers.cookie
      : undefined
 ```

2022-07-04 00:38 UTC, dthyresson approved these changes

2022-07-04 00:42 UTC, alicelovescake commented on packages/api/src/functions/dbAuth/shared.ts
> +  if (typeof text === 'undefined' || text === null) {
@dthyresson do we still need to add the null check if we return undefined instead of null in the ternary of `cookieFromGraphiqlHeader`?

2022-07-04 00:43 UTC, dthyresson commented on packages/api/src/functions/dbAuth/shared.ts
> +  if (typeof text === 'undefined' || text === null) {
Not sure. I had to add that check because tests fail. If you think it can be removed, then please do and re-run tests. Thanks!

2022-07-04 00:48 UTC, alicelovescake commented on packages/graphql-server/src/functions/graphql.ts
> +  createServer,
ah yes, missed the type. I thought we had duplicate imports. Thanks for the catch!

2022-07-04 00:51 UTC, alicelovescake commented on packages/api/src/functions/dbAuth/shared.ts
> +  if (typeof text === 'undefined' || text === null) {
Yeah I think you are right. Not sure why tests are not passing if we take out the null check but just added it back!

2022-07-04 01:16 UTC, dthyresson approved these changes

2022-07-04 05:04 UTC, alicelovescake commented
@dthyresson made some minor fixes to get the tests passing. I don't have write access so if you think it looks good, you can merge!

2022-07-04 11:13 UTC, merged