fix: check for edge cases on resolve union type
redwoodjs/redwood pull request #5752
Opened 2022-06-13 05:01 UTC by alicelovescake

This PR resolves #5661 with the following changes:

- [x] Checks for typename first if it exists on the returned object
- [x] If typename does not exist, we check for max intersecting fields
- [x] If max # of intersecting fields is not a unique number. i.e if the object has 2 fields in common with type 1 and type 2, we are unable to resolve the type of the object

2022-06-27 16:12 UTC, dthyresson commented
Feedback from checking - needs a test. See the example app fixtures.

2022-07-04 18:48 UTC, alicelovescake commented
> Let's add a test for this case @alicelovescake. Thanks!

@dthyresson Added tests! I also chatted with @jtoar and added the implementation back for throwing an error if types cannot be resolved. In my latest commit, there are tests for both checking for typename and if fields cannot be resolved.

2022-07-11 09:45 UTC, jtoar requested changes
Thanks @alicelovescake, tests looks good. We're nearly there! Just had a suggestion about the copy for the error, and a question about object properties.

2022-07-11 09:45 UTC, jtoar commented on packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
> +    if (Object.prototype.hasOwnProperty.call(obj, '__typename')) {
Only suggesting this cause I had to look stuff up, but MDN recommends we use `Object.hasOwn` instead: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn

<img width="757" alt="image" src="https://user-images.githubusercontent.com/32992335/178233415-341f8a79-a439-4d44-8f89-a952aabc97f5.png">

```suggestion
    if (Object.hasOwn(obj, '__typename')) {
```

But do we need to be this safe here? (I.e., we can't use `in`?) Better safe than sorry for sure, but I had a look at `obj.__proto__` in the example tal posted and it was `null`. But not sure if that was specific to that example or not. 🤔

2022-07-11 09:45 UTC, jtoar commented on packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
>          (field) => field in obj
In a similar vein to my previous comment, now that I'm thinking about it, should we use `Object.hasOwn` here too or does it not matter?

2022-07-11 09:45 UTC, jtoar commented on packages/graphql-server/src/makeMergedSchema/makeMergedSchema.ts
> +        'Unable to resolve correct type for union. Try adding unique fields or __typename to each type'
> or __typename to each type

This sounds like you should edit the SDL, and you're definitely not allowed to add fields to types that start with `__`. So let's mention resolvers instead, or just remove it.

We'll have to update the test too!

```suggestion
        'Unable to resolve correct type for union. Try adding unique fields to each type or __typename to each resolver'
```

2022-07-11 09:45 UTC, jtoar commented on packages/graphql-server/src/makeMergedSchema/__tests__/makeMergedSchema.test.ts
> +          'Unable to resolve correct type for union. Try adding unique fields or __typename to each type'
```suggestion
          'Unable to resolve correct type for union. Try adding unique fields to each type or __typename to each resolver'
```

2022-07-16 14:57 UTC, jtoar approved these changes
Great work @alicelovescake! 🚀

2022-07-16 14:59 UTC, merged