DRAFT: Configure Fastify Server with Custom Plugins and Routes
redwoodjs/redwood pull request #5903
Opened 2022-07-11 18:31 UTC by dthyresson

This PR addresses the core issue noted in:

* https://github.com/redwoodjs/redwood/issues/4944
* https://github.com/redwoodjs/redwood/issues/5215

As @tbay06 noted:

> I've been using the server.config.js to play with some of the fastify settings, and I'm not sure how difficult/intensive it would be, but being able to enrich the fastify instance with some plugins via the config would be a really cool feature! Right now from what I can see the server.config.js exposes all of the [factory settings]

> (https://www.fastify.io/docs/latest/Reference/Server/#factory) for fastify, but if we were able to access the instance methods as well, that would open up a lot of awesome customization options.

Agreed!

> being able to enrich the fastify instance with some plugins via the config would be a really cool feature

The `server.config` now exposes a hook that configure plugins or routes per side.

See included docs for examples.

TODO:

* [ ] Review with @dac09 
* [ ] Add tests once functions finalized
* [ ] Update docs for changes
* [ ] figure out how to handle errors like duplicated plugin registration better

2022-07-11 19:57 UTC, dac09 commented on docs/docs/app-configuration-redwood-toml.md
> + :::note
Needs a space for it t owork I think

2022-07-11 20:02 UTC, dac09 commented on packages/api-server/src/__tests__/withFunctions.test.ts
> +  const log = mockedFastifyInstance['log']['_buffer']
I think these tests can probably made less flakey.

2022-07-12 21:02 UTC, dac09 commented on docs/docs/app-configuration-redwood-toml.md
> +You will need to install any custom plug-in packages to your project's `api` workspace.
```suggestion
You will need to install any custom plug-in packages to your project's `api` workspace.

To do this you run `yarn workspace api add @fastify/rate-limit @fastify/compress`
```

2022-07-18 14:50 UTC, dthyresson commented
Note, no longer want to showcase route config, so updated title.

2022-07-20 21:58 UTC, dac09 commented on packages/api-server/src/requestHandlers/awsLambdaFastify.ts
> +const mergeMultiValueHeaders = (
Are you sure there are cases where multivalue headers are present and headers aren't? 

My understanding is that MVH are duplicated - its just a proxy setting.

2022-07-20 21:59 UTC, dac09 commented on packages/api-server/src/requestHandlers/awsLambdaFastify.ts
> +const sanitizeHeaders = (
As explained in the fastify issue - they've implemented this as a performance optimisation to only support lower case headers. Why do we need to sanitise them here? Just adds extra loops right?

2022-07-20 21:59 UTC, dac09 requested changes
Comments inline - not sure about MVH and sanitizeHeader changes

2022-07-21 16:54 UTC, dac09 commented on packages/api-server/src/requestHandlers/awsLambdaFastify.ts
> +const mergeMultiValueHeaders = (
Resolving as this is definitely required!

2022-07-21 16:55 UTC, dac09 commented on packages/api-server/src/requestHandlers/awsLambdaFastify.ts
> +const sanitizeHeaders = (
DT will remove the PascalCase ContentType from our graphql function, and dbAuth.

2022-07-25 17:33 UTC, dthyresson commented
> Comments inline - not sure about MVH and sanitizeHeader changes

No longer sanitizing headers as these will be standard lowercase in dbAuth and GraphQL Server.

Added tests for MVH and also in the Lambda request transform that MVH are converted into headers.

2022-07-25 17:44 UTC, dthyresson commented
This PR also:

Updates api-server to latest Fastify v4.x

Main change was to the fastify-raw-body plugin that now requires an await.

See:

Note
You need to await the plugin registration to make sure the plugin is ready to use. All the routes defined before the plugin registration will be ignored. This change has been introduced in Fastify v4.
If not, then the body is empty and all GraphQL and other functions fail.

Includes

Fixes https://github.com/redwoodjs/redwood/pull/5718
Fixes https://github.com/redwoodjs/redwood/pull/5724
Fixes https://github.com/redwoodjs/redwood/pull/5723
Fixes https://github.com/redwoodjs/redwood/pull/5585

2022-07-27 15:17 UTC, dac09 commented on packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.ts
> +  ast.find(j.ExpressionStatement).forEach((path) => {
Bit of a nitpick, so ok if you want to dismiss, but you could just do j.AssignmentExpression here... or even better if we used `j.ExportDeclaration

2022-07-28 16:32 UTC, dac09 commented on packages/codemods/src/codemods/v2.x.x/configureFastify/configureFastify.ts
> +  ast.find(j.ExpressionStatement).forEach((path) => {
Realised j.ExportDeclaration won't work here, but worth a check if we can make it more specific

2022-07-29 10:07 UTC, dthyresson commented
@dac09 I think these final tests will soon pass and can merge.

2022-07-29 10:35 UTC, dac09 commented
Still seeing lint errors @dthyresson - unused imports and such. I'll fix it - but I think maybe your editor isn't showing these for you.

2022-07-29 10:37 UTC, dac09 approved these changes

2022-07-29 10:37 UTC, merged