fix(graphql): Fixes multiValueHeader handling (and CORS) in graphql handler
redwoodjs/redwood pull request #5970
Opened 2022-07-15 22:26 UTC by dac09

Fixes #5933

2022-07-18 14:42 UTC, dthyresson requested changes
Thanks. Just minor word-smithing.

2022-07-18 14:42 UTC, dthyresson commented on packages/graphql-server/src/__tests__/cors.test.ts
> +    multiValueHeaders: {}, // this is stupid. but that's what they types say. It definitely can be null, e.g. on Vercel
```suggestion
    multiValueHeaders: {}, // this is stupid. But, that's what the types say. It definitely can be null, e.g. on Vercel.
```

2022-07-18 14:42 UTC, dthyresson commented on packages/graphql-server/src/functions/graphql.ts
> +    // But this isn't true on Vercel, its just undefined.
```suggestion
    // But this isn't true on Vercel, it's just undefined.
```

2022-07-19 20:07 UTC, merged

2022-07-21 15:38 UTC, dac09 commented
>  have no idea how you debugged this one 

Blood, sweat and tears.... Half the effort was figuring out how to debug it! patch package comes in handy in these situations