Fix #6374 - Render.com web builds fail
redwoodjs/redwood pull request #6375
Opened 2022-09-10 00:28 UTC by shansmith01

See #6374 re Render.com web build fails due to only supporting yarn 1.

Updated the template file so others don't have the same issue

2022-09-10 07:27 UTC, noire-munich commented
@simoncrypta I've assigned you as you are assigned to the issue - thought we should be consistent ( and maybe double check the bot?)

2022-09-10 21:18 UTC, simoncrypta commented
@shansmith01 Thanks for that ! This cause so much trouble for everyone and this trick is not really well documented. So since we use yarn 3 by default, we should also skip dep sync for Render by default. Good job ! 

@noire-munich All right, I will check if we can update the bot for that. 🙂

2022-09-13 19:02 UTC, simoncrypta requested changes

2022-09-13 19:10 UTC, shansmith01 commented on packages/cli/src/commands/setup/deploy/templates/render.js
> +  buildCommand: yarn; yarn rw deploy render web
Makes sense to me

2022-09-13 19:56 UTC, simoncrypta approved these changes
Works like a charm, thanks a lot !

2022-09-13 20:22 UTC, merged