Add back `buildType: nixpacks` per Flightcontrol request
redwoodjs/redwood pull request #7598
Opened 2023-02-09 12:19 UTC by schybo

Following up from the [issue here ](https://github.com/redwoodjs/redwood/issues/7597#issuecomment-1424054130) where the default `flightcontrol.json` no longer works after upgrading to RedwoodJS 4. Seems like the `buildType: 'nixpacks'` option was removed in [this PR](https://github.com/redwoodjs/redwood/pull/6941) (unsure why it was - seems the [issue](https://github.com/redwoodjs/redwood/issues/6927) it was solving only needed the `postBuildCommand` be removed.

Regardless, after discussing with the Flightcontrol team, we needed to get that added back for builds to work such that the node version would be respected and not fail on the null coalescing operator that was only introduced in node 15.

2023-02-09 12:43 UTC, flybayer requested changes
awesome! We had to remove it before because it was unsupported at that time.

2023-02-09 12:43 UTC, flybayer commented on packages/cli/src/commands/setup/deploy/templates/flightcontrol.js
>              'yarn set version stable && NODE_ENV=development yarn install',
```suggestion
```

2023-02-10 02:58 UTC, flybayer approved these changes

2023-02-10 03:00 UTC, merged

2023-02-10 03:37 UTC, jtoar commented
@schybo this fix was just released in v4.1.2 https://github.com/redwoodjs/redwood/releases/tag/v4.1.2

2023-02-10 11:25 UTC, schybo commented
Thanks @jtoar