feat: RedwoodJS Studio & OpenTelemetry (Dev)
redwoodjs/redwood pull request #7829
Opened 2023-03-15 21:17 UTC by Josh-Walker-GM

## RedwoodJS Studio
This PR adds the initial experimental version of a "RedwoodJS Studio". This is a CLI command `yarn rw studio` which spans a development studio which users can use to gain insights into their project via the OpenTelemetry instrumentation. 

**Features**
- Tracing page which lists all the ingested OpenTelemetry traces and trace visualisation via three modes; timeline, flame table and prisma queries
- SQL page which exposes a list of all the queries/statements made
- GraphiQL page which allows access to the standard GraphiQL interface but also is able to support basic user impersonation.

**Setup / Requirements**
There is not explicit setup of the studio required. You will need to have setup OpenTelemetry to enable the studio to gather the data it uses to provide you with insights into your project. 

**Config**
We have adding some optional settings to the redwood.toml file. See below for the options added with descriptions of their purpose.

```toml
[studio]
  # Determines whether the studio should run with an in memory database or persist the data
  # to a file in your project within `./redwood` 
  inMemory = false

  # The auth provider used within your project that GraphiQL should understand and use to
  # impersonate users
  authProvider = "dbAuth"

  # The user ID of the impersonation user that GraphiQL uses
  userId = "1"

  # The user roles of the impersonation user that GraphiQL uses
  roles = ["a", "b"]
```

## OpenTelemetry Support
This PR also adds support for OpenTelemetry instrumentation of components of the framework. I exposes a setup command which generated the boilerplate needed to gather instrumentation from the API side of a redwood project: `yarn rw setup opentelemetry`

⚠️ - This is currently only supported during development. Enabling OpenTelemetry in production will be out next work after this but will require other structural changes to the framework/deployments. 

**Features**
- Sets up an OpenTelemetry sdk file which should provide a boilerplate which enables gathering tracing from your project
- The graphql yoga server now is instrumented with OpenTelemetry via an envelop plugin
- API functions are automatically wrapped to produce OpenTelemetry spans via a babel plugin

**Setup / Requirements**
`yarn rw setup opentelemetry` should perform all the necessary setup needed to enable gathering OpenTelemetry traces from your project. 

This will add the necessary dependencies to your project and produce an `opentelemetry.ts|js` file within your API side. This file is where your SDK is setup to collect and export the telemetry generated by your Redwood app. By default your telemetry will be exported to `http://localhost:4318/v1/traces` you can change to suit your needs. This is the location that Redwood Studio will listen for traces so leave this as the default if you wish to use the studio.

**Config**
You should be able to configure the behaviour of OpenTelemetry from within the `opentelemetry.ts|js` file which was generated. There is one additional TOML field which will be setup which is used to inform Redwood of where this setup file lives: 
```toml
[opentelemetry]
  scriptPath = "/home/linux-user/redwood-project/api/src/opentelemetry.js"
```

---

## Pull Request - Outstanding Work

1. Avoid CORS setup needed by graphiql by using an API proxy on the studio backend.
2. Documentation
   1. RedwoodJS Studio
   2. OpenTelemetry setup  

Ping: @dthyresson

2023-03-15 22:20 UTC, Josh-Walker-GM commented on packages/studio/backend/lib/authProviderEncoders/netlifyAuthEncoder.ts
> +  const token = jwt.sign(payload, 'secret')
@dthyresson We're good with this because we're actually trying to produce a fake hardcoded cred here correct?

2023-04-03 18:23 UTC, dthyresson commented
@dthyresson TODO. fixed code security secret by throwing error if undefined instead,

2023-04-03 22:08 UTC, dthyresson approved these changes
Approved! Great work and excited to show the community

2023-04-04 18:02 UTC, thedavidprice requested changes
Great work on this @Josh-Walker-GM 🚀

This needs to be clearly marked as Experimental: we are not guaranteering it will become a feature and we need (if applicable) to break things outside of semver releases.

Can you please update the README to indicate it's experimental and the brief rationale above?

Also, do you think we can follow the pattern for TOML we discussed, so something like `[experimental.studio]`? (And/or were you planning to do that?) Just confirming as I understand this README is documentation.

2023-04-05 19:48 UTC, Josh-Walker-GM commented
> Great work on this @Josh-Walker-GM 🚀
> 
> This needs to be clearly marked as Experimental: we are not guaranteering it will become a feature and we need (if applicable) to break things outside of semver releases.
> 
> Can you please update the README to indicate it's experimental and the brief rationale above?
> 
> Also, do you think we can follow the pattern for TOML we discussed, so something like `[experimental.studio]`? (And/or were you planning to do that?) Just confirming as I understand this README is documentation.

Hey @thedavidprice, yeah I made the following changes which should have hopefully moved this in the direction you requested:

1. TOML options are now prefixed with `experimental` so they look like the following:
```toml
[experimental.opentelemetry]
  enabled = true
  apiSdk = "/home/josh/Development/redwood-test-project/api/src/opentelemetry.js"
```

2. Commands now have an `experimental` prefix so they look like the following:

https://user-images.githubusercontent.com/56300765/230188393-eac0ecf8-804d-412b-8b54-df4c53386cbf.mp4


This should provide the following benefits:

1. It is clear to the user which TOML is for experimental features. We can state clearly that any TOML with an `experimental` prefix does not follow SEMVER and can/will break, change or be deprecated often. 
2. Experimental CLI commands are not only obviously experimental given the prefix but are also discoverable in the standard yargs way - i.e. providing now command will list the available commands as shown in the demo above.

--- 

I will update the readme to be explicit in its "experimental" status and will also add links to forum pages for both CLI commands. 

Sound/look good?

2023-04-05 20:35 UTC, thedavidprice approved these changes
@Josh-Walker-GM Yes to all the above! Screen recording is exciting 🚀

My only 2¢ is to provide an alias for the `yarn rw experimental [command]` so users could type in something like `yarn rw exp [command]`. I defer to you.

Plan == approved.

2023-04-05 20:55 UTC, Josh-Walker-GM commented
Alias is a good idea! Added it in as `exp`

2023-04-16 20:45 UTC, merged