chore(rwfw): working refactor, make `project:sync` ignore more files
redwoodjs/redwood pull request #8579
Opened 2023-06-09 20:50 UTC by jtoar

When I clean the framework so that build has to happen from scratch instead of pulling from the cache, I can reproduce `yarn rwfw project:sync` failing with:

```
rwfw  /<path>/redwood/packages/cli-packages/storybook/meta.json
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '<path>/redwood/packages/cli-packages/package.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at packageJsonName (file:///<path>/redwood/tasks/framework-tools/lib/framework.mjs:146:24)
    at FSWatcher.<anonymous> (file:///<path>/redwood/tasks/framework-tools/frameworkSyncToProject.mjs:100:25)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher.emitWithAll (/<path>/redwood/node_modules/chokidar/index.js:541:32)
    at awfEmit (/<path>/redwood/node_modules/chokidar/index.js:607:14)
    at /<path>/redwood/node_modules/chokidar/index.js:728:9
    at FSReqCallback.oncomplete (node:fs:209:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/<path>/redwood/packages/cli-packages/package.json'
}
```

I'm not sure exactly why this is happening still, but the code here could be stricter about when it ignores, and so far these changes seem to fix it. There's still a couple more quality of life changes I'd like to make, but mostly just opened this now for @KrisCoulson to test locally.

2023-06-09 23:51 UTC, jtoar commented on tasks/framework-tools/lib/framework.mjs
> -    ['--parallel', `--scope={${packageNames.join(',') + ','}}`],
Nx issues a warning that this option doesn't do anything anymore

2023-06-09 23:51 UTC, jtoar commented on tasks/framework-tools/lib/test.mjs
Ignore this file, I'll remove it

2023-06-12 23:15 UTC, thedavidprice approved these changes
Local QA == ✅

Steps:
- create redwood app for new project at 5.3.0
- check out PR branch
- git clean -fxd -e .env
- yarn
_from Project directory_
- yarn rwfw project:sync
<img width="381" alt="Screenshot 2023-06-12 at 4 10 03 PM" src="https://github.com/redwoodjs/redwood/assets/2951/ea05eccb-6b86-44c2-850f-1f1aa07b908b">

2023-06-13 01:20 UTC, thedavidprice requested changes
Well, blast. 👎 Per request to also [test file changes over here in #8580](https://github.com/redwoodjs/redwood/issues/8580#issuecomment-1588260432), I now get the error message _after_ sync is successful but I then edit and save a file. To reproduce:
- `yarn rwfw project:sync` (successful)
- edit `packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts`

Fails with the error message below. 

```
rwfw  Waiting for changes
-------------------------------------------------------------------------------------------------------------
rwfw  /Users/price/Repos/redwoodjs-redwood/packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts changed
rwfw  Restoring the Redwood project's package.json...

To get your project back to its original state...
- undo the changes to project's your yarn.lock file
- remove your project's node_modules directory
- run 'yarn install'

rwfw  Closing the watcher...
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: /Users/price/Repos/redwoodjs-redwood/packages/auth-providers/package.json: ENOENT: no such file or directory, open '/Users/price/Repos/redwoodjs-redwood/packages/auth-providers/package.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Object.readFileSync (/Users/price/Repos/redwoodjs-redwood/node_modules/jsonfile/index.js:50:22)
    at getPackageJsonName (file:///Users/price/Repos/redwoodjs-redwood/tasks/framework-tools/lib/framework.mjs:161:13)
    at FSWatcher.<anonymous> (file:///Users/price/Repos/redwoodjs-redwood/tasks/framework-tools/frameworkSyncToProject.mjs:234:25)
    at FSWatcher.emit (node:events:513:28)
    at FSWatcher.emitWithAll (/Users/price/Repos/redwoodjs-redwood/node_modules/chokidar/index.js:541:32)
    at awfEmit (/Users/price/Repos/redwoodjs-redwood/node_modules/chokidar/index.js:607:14)
    at /Users/price/Repos/redwoodjs-redwood/node_modules/chokidar/index.js:728:9
    at FSReqCallback.oncomplete (node:fs:209:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/price/Repos/redwoodjs-redwood/packages/auth-providers/package.json'
}

Node.js v18.16.0
```

2023-06-13 03:07 UTC, jtoar commented
Thanks @thedavidprice and @arimendelow, I realize there's an error in the `resolvePackageJsonPath` now

2023-06-13 05:19 UTC, jtoar commented
@arimendelow I think I've address the issue if you wouldn't mind trying again whenever you have time

2023-06-13 05:36 UTC, arimendelow commented
ah it works!!! thanks @jtoar 🙂 i really appreciate how quickly you fixed this

<img width="1005" alt="Screenshot 2023-06-12 at 10 35 50 PM" src="https://github.com/redwoodjs/redwood/assets/16390116/a0f98435-6239-44ee-be82-93b7c1a90934">

2023-06-13 19:40 UTC, merged