dbAuth: Allow running multiple RW apps at the same time
redwoodjs/redwood pull request #9248
Opened 2023-10-02 00:11 UTC by Tobbe

Previously you couldn't run two different RW apps at the same time (by using different ports) when using dbAuth.
dbAuth in one app would overwrite the session cookie used by the other app, and vice versa. The reason is that they both used the same cookie name (`session`), and browsers only separate cookies by host name, not port.

This PR reads the port an app is running on from `redwood.toml` and includes that in the cookie name. It also adds `dbauth_` to the start of the cookie name to make it less likely the name conflicts with some other service running on the computer.
So the final cookie name will be something like `dbauth_session_8911` now.

2023-10-05 16:08 UTC, cannikin requested changes
One major concern: pushing this to production will log out all of your users. Some people like long-lived cookies so their users rarely/never have to log in. I suggest we avoid doing this, especially if we can prevent it. It's good that you can override this behavior by setting the ENV var, but you could easily overlook/forget that step and it happens anyway. But it's an easy thing to prevent on our end:

How about not changing the cookie name in production and only append the port in non-prod environments (and could probably skip prepending `dbauth_` altogether). So `session_8911` in dev/test and just `session` in prod. 

A minor concern with prepending `dbauth` is it now makes it very clear what your auth strategy is, and a bad actor could use that knowledge to start looking for exploits. `session` is generic and doesn't give anything away. (If we only prepended it in dev, that would remove that concern, of course.)

One last thing: I think we should let the user set the cookie name along with the rest of the auth config that's generated in `api/src/functions/auth.js`. Otherwise we're saying "do absolutely ALL of your auth config right here! (except for this *one* thing, that goes somewhere else)".

2023-10-05 16:18 UTC, Tobbe commented
I added the env var exactly for this reason. If people don't read the upgrade notes that's in them?
I'm happy to get rid of the dbauth prefix
Not adding the port in prod makes it impossible to run two dbauth apps on the same host in production. If we make that the default I'd like to come up with a way to set the cookie name per app in production. Maybe we can add a setting to redwood.toml?

2023-10-05 16:22 UTC, cannikin commented
I edited my response above with more context about everything, sorry I didn't get it in there right away!

Yeah our release notes are always awesome, but I think it's too easy to miss and log everyone out, which someone people would *hate*. And it's really easy to avoid on our end by just keeping the default name in prod.

And yes, I love the idea of letting people name the cookie per-app (I should have had this in the initial release, my bad for overlooking it!). I'd suggest we let people do that in the generated `api/src/functions/auth.js` file along with all of the other auth config.

2023-10-06 17:31 UTC, cannikin approved these changes
LOVE IT Yeah this feels great, existing apps are fine, but new apps get the new behavior. And setting the name of the cookie happens with the other dbAuth config. SHIP IT

2023-10-06 17:45 UTC, merged

2024-11-23 22:11 UTC, Philzen commented
As some of the cookie config values are were deprecated (moved into `cookie.attributes`) shouldn't these update notes be mentioned in the [v6 release note](https://community.redwoodjs.com/t/redwood-v6-0-0-upgrade-guide/5044)?