📝 WIP: Added page for using GitPod to the documentation
redwoodjs/redwood pull request #9366
Opened 2023-10-31 22:06 UTC by ahaywood

## Feature description

- Added information about using Redwood in GitPod on the Getting started page of the documentation
- Added a dedicated page to the documentation for working with GitPod

- [ ] Need to add a 3 minute video to the dedicated GitPod page explaining how to get from fork to first commit
- [ ] Need to add a 3 minute video giving a brief tour of GitPod

2023-10-31 22:09 UTC, ahaywood commented
The images that I reference within the dedicated GitPod page are pointing to the images on the [redwoodjs/starter repo](https://github.com/redwoodjs/starter)

Question: This makes sense since this page of documentation is dependent on that repo. If the images in the starter repo change then should change within the documentation too. However, this also seems fragile and a point of failure. Should I duplicate the images, placing them in both repos?

2023-12-20 22:00 UTC, jtoar requested changes
@ahaywood nice! Left some comments; may seem like a lot but it's mostly

- consistent GitPod casing (the majority of comments)
- some images/buttons don't seem to be rendering (included screenshots where appropriate)

I merged main into your branch so that I could get deploy previews going here: https://deploy-preview-9366--redwoodjs-docs.netlify.app/docs/canary/how-to/using-gitpod.

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +# Using Gitpod
```suggestion
# Using GitPod
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +## What is Gitpod?
```suggestion
## What is GitPod?
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +Gitpod is a cloud development environment with all the necessary tools and dependencies, allowing you to focus on building your RedwoodJS application without worrying about the setup. Get started qui
```suggestion
GitPod is a cloud development environment with all the necessary tools and dependencies, allowing you to focus on building your RedwoodJS application without worrying about the setup. Get started quickly and efficiently by launching RedwoodJS inside GitPod!
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +Click on the Open in Gitpod button:
```suggestion
Click on the Open in GitPod button:
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/redwoodjs/starter)
```suggestion
[![Open in GitPod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/redwoodjs/starter)
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +- GitPod is setting the workspace set up
This reads a little awkward. Did you mean setting up the workspace?

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +Changes the database to a postgres database
Does this need to be part of the list?

```suggestion
- Changes the database prover to Postgres
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +Once everything is up and running, you can click on the Ports tab
```suggestion
Once everything is up and running, you can click on the Ports tab:
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +![Port 8910 frontend](https://github.com/redwoodjs/starter/raw/main/images/gitpod-port-8910.png)
Adding a space just to match the others in this list:

```suggestion
- Port 8910 is your frontend

![Port 8910 frontend](https://github.com/redwoodjs/starter/raw/main/images/gitpod-port-8910.png)
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +## How to Use Gitpod
```suggestion
## How to Use GitPod
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +If you have an existing project, you can still use Gitpod.
```suggestion
If you have an existing project, you can still use GitPod:
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +1. Take any repository within GitHub and append `gitpod.io/#` to the URL. This will quickly launch a Gitpod workspace.
```suggestion
1. Take any repository within GitHub and append `gitpod.io/#` to the URL. This will quickly launch a GitPod workspace.
```

2023-12-20 22:00 UTC, jtoar commented on docs/docs/how-to/using-gitpod.md
> +[![GitPod Ports Tab](https://github.com/redwoodjs/starter/blob/main/images/gitpod-ports.png)]
This image isn't rendering in the docs for some reason:

<img width="631" alt="image" src="https://github.com/redwoodjs/redwood/assets/32992335/2f303a0a-5cfd-43f0-99f8-98d7953234ef">

2023-12-20 22:00 UTC, jtoar commented on docs/docs/quick-start.md
> +![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/redwoodjs/starter)
This isn't rendering too well:

<img width="631" alt="image" src="https://github.com/redwoodjs/redwood/assets/32992335/223ff06a-0eba-4996-9975-e0edc20f18b1">

2024-06-26 07:35 UTC, Tobbe commented
@ahaywood Is this still relevant? If it is, do you need any help getting it merged?

2024-07-19 23:58 UTC, Josh-Walker-GM approved these changes
Awesome. I implemented Dom's suggestions and walked through the process. I had to update the starter repo to bump the version of node used to v20 but otherwise went great.

2024-07-20 00:02 UTC, merged