fix(context): Expand API context isolation to cover all functions
redwoodjs/redwood pull request #9371
Opened 2023-11-02 15:15 UTC by Josh-Walker-GM

**Problem**
Context isolation was partially updated in v6 to remove a legacy flag which allowed disabling of context isolation. This unfortunately introduced some bugs for users which could not be further addressed without more potentially breaking changes. These were mainly centred around users who had introduced their own context isolation/handling into non-graphql functions.

Functions (other than graphql) have never had the assurance of context isolation out of the box - even though we allow direct access to the context in a function like we do in other places such as services. This is clear when you look at the results of k6 tests which test context isolation:
![image](https://github.com/redwoodjs/redwood/assets/56300765/19500bbe-6ef3-4d50-b7f6-1537c137ca66)
I do not think this is behaviour we should support. It makes it easy to introduce information leakage between requests and is a confusing disparity in behaviour between graphql and other functions.

**Changes**
1. Moves context code into it's own package `@redwoodjs/context`. This is to avoid circular dependencies when it lives in either `@redwoodjs/api-server` or `@redwoodjs/graphql-server`. It is also a small package with no external dependencies which also helps to avoid bringing in unneeded code should it live in somewhere like `@redwoodjs/api` - although I am happy to move this into that package should we feel it'll only ever be used in conjunction with it.
2. Updates the context isolation mocking during user project tests.
3. Updates the context isolation tests in the test-project fixture.
4. Updates k6 tests to reference the new context package.

**TODO**
1. I want to confirm this plays nicely with users who have been using context in their api side tests.
2. I want to go through and tidy up any of this code which could do with it. We can likely deduplicate some code but I don't want to step on any of the other ongoing api server refactoring.
3. I also want to rename away from `GlobalContext` to something more descriptive like `RedwoodAPIContext` or similar.

2023-11-12 19:57 UTC, Josh-Walker-GM commented
Testing again with k6 tests shows that context works for the following:
```
yarn rw serve
yarn rw serve api
yarn rw dev
yarn rw-server
yarn rw-server api
```
The p(90) of the request durations where also pretty much the same before and after the changes added here. Of course this is all local and not results from deployed apps.

2023-12-24 02:30 UTC, Josh-Walker-GM commented
@Tobbe and I discussed this PR and the suggestion was that we attempt to make this not breaking. We restore the original files in the `graphql-server` package so they remain for anyone using them but are marked deprecated.

I can't guarantee it is not breaking for people who have used our context related code within their own app in an attempt to get context working outside graphql. In this case they should be able to fix any issues by removing their custom code and relying on the functionality now being provided by the framework.

2023-12-25 16:32 UTC, Tobbe requested changes

2023-12-25 16:32 UTC, Tobbe commented on packages/graphql-server/src/globalContext.ts
> + * @deprecated This type will be available only from the `@redwoodjs/context` in a future release.
```suggestion
 * @deprecated This type will be available only from the `@redwoodjs/context` package in a future release.
```

2023-12-25 16:32 UTC, Tobbe commented on packages/graphql-server/src/globalContext.ts
> + * @deprecated This function will be available only from the `@redwoodjs/context` in a future release.
```suggestion
 * @deprecated This function will be available only from the `@redwoodjs/context` package in a future release.
```

2023-12-25 16:32 UTC, Tobbe commented on packages/graphql-server/src/globalContext.ts
> + * @deprecated This value will be available only from the `@redwoodjs/context` in a future release.
```suggestion
 * @deprecated This value will be available only from the `@redwoodjs/context` package in a future release.
```

2023-12-25 16:32 UTC, Tobbe commented on packages/graphql-server/src/globalContext.ts
> + * @deprecated This function will be available only from the `@redwoodjs/context` in a future release.
```suggestion
 * @deprecated This function will be available only from the `@redwoodjs/context` package in a future release.
```

2023-12-25 16:32 UTC, Tobbe commented on packages/graphql-server/src/globalContextStore.ts
> + * @deprecated This function will be available only from the `@redwoodjs/context` in a future release.
```suggestion
 * @deprecated This function will be available only from the `@redwoodjs/context` package in a future release.
```

2023-12-25 16:32 UTC, Tobbe commented on packages/context/README.md
> +**WIP**: This package is still a work in progress.
Remove WIP and replace by proper content

2023-12-25 16:55 UTC, Tobbe approved these changes

2023-12-25 17:23 UTC, merged